### ISSUE TITLE
Add a dashboard for the app

### ISSUE THREAD

**Issue by bedouijesser** [AymKh/CTF-KH-Basic#12]
## Detailed Description
A dashboard can be useful to serve a multitude of functions, and thus improving the feel and quality of the interface resulting in a better application in all.

## Context
What are the benefits of adding a dashboard I hear you mumbling to yourself ?
here's a list of what I can think of right now  :  

- [ ] monitor other participants progress and overall ranking
- [ ] get a feel for the depth of the CTF and perhaps complexity of each challenge
- [ ] get a deep analysis of the performance of the participant, misses, time taken ...
- [ ] get a real-time feedback on who captured the flag first, useful for live events

**Comment by AymKh** [comment]
I will be wrking on a dhashboard + scoreboard system as soon as I implement oauth
